### ISSUE TITLE
PLG_SYSTEM_SIWECOS_API_ERROR

### ISSUE THREAD

**Issue by Kime203** [SIWECOS/siwecos-joomla#2]
When I enter and save my email address and password I get this error message PLG_SYSTEM_SIWECOS_API_ERROR

**Comment by SniperSister** [comment]
We are doing some maintenance work on the API right now, please give it another try later today.

**Comment by HLeithner** [comment]
With commit https://github.com/SIWECOS/siwecos-joomla/commit/ed5a8a1e0d5d2bf69b1cf3440c9e36297b7c6e1d we should get a error message

**Comment by Kime203** [comment]
API Error is now %s

**Comment by SniperSister** [comment]
Does it work if you use tool on SIWECOS.de with the same domain?

**Comment by Kime203** [comment]
With the SIWECOS quick-check it works at this domain.

**Comment by HLeithner** [comment]
good... with the currecnt version you should get at least the error code. https://github.com/SIWECOS/siwecos-joomla/commit/dc7551feddd9209326645a0b5d944ab327946b80

**Comment by Kime203** [comment]
400

**Comment by SniperSister** [comment]
Weird! Can you do me a favour and email me your site's credentials (SFTP/FTP and Joomla) to david.jardin@community.joomla.org so I can debug this?

**Comment by SniperSister** [comment]
Fixed with 8f844ee95e485bfb853745feb9cb924faf1d48df

Thanks for your help!
