### ISSUE TITLE
Error: Username and password do not match

### ISSUE THREAD

**Issue by ReLater** [SIWECOS/siwecos-joomla#3]
Tested with Joomla 3.8.8 and 3.8.11-dev
- I've created an account at siwecos.de and could login and run a scan without any issues for a verified site.
- The password was
`Dp{r/uMP5TL;<B%Hqhs"HI0g@h|{lILs`
- Afterwards I installed your plugin 1.0.1 in backend of this site and entered the same credentials.

When saving the plugin I get:
```
Error
Save failed with the following error: Username and password do not match or you do not have an account yet.
```
and the password becomes:
`Dp{r/uMP5TL;B%Hqhs"HI0g@h|{lILs`
(missing `<`)

**Comment by HLeithner** [comment]
Thx, seams that thr joomla input filter removed it, I will look at it.

**Comment by SniperSister** [comment]
raw filter was missing on the password field.

@ReLater can you update your siwecos.xml accordingly and give it a try, if that solves the bug?

https://github.com/SIWECOS/siwecos-joomla/commit/a4dc41c1f577fc833f7c9776717ec130185157db

**Comment by ReLater** [comment]
Pr successfully tested with password containing `<` and `>`.

(Just confusing before I started to think about the tokens: I could start a new scan via module without changing the password in plugin before. )

**Comment by ReLater** [comment]
Close because fixed by https://github.com/SIWECOS/siwecos-joomla/commit/a4dc41c1f577fc833f7c9776717ec130185157db
